### ISSUE TITLE
[PE-D][Tester F] Wrong error message when adding names with special characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-4/tp#219]
Can possibly consider a error message that says "special characters not allowed"
![Picture6.png](https://raw.githubusercontent.com/testing1234567891011121314/ped/main/files/1a15be8d-5428-43ee-887b-77f81c299545.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: testing1234567891011121314/ped#5

**Comment by Oceankoh** [comment]
Hi the error message you're receiving is not due to the special characters in the name, rather it is because you are trying to add a new person with a duplicate email and course. Special characters like `@` are intentionally allowed becuase the @ symbol represents an alias which can be in your legal name.
